# -*- coding: utf-8 -*-


# Form implementation generated from reading ui file 'scroll_delete.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import  QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog, QTextEdit, QScrollArea, QVBoxLayout, QPushButton, QLabel, QApplication
import os
from openpyxl import Workbook
from docx import Document
from datetime import date
from create_data_base import Data_base_meth


class Scroll_delete(QDialog):
    def __init__(self):
        super().__init__()
        self.setupUi(self)
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(446, 346)
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 300, 241, 32))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 0, 125, 16))
        self.label.setObjectName("label")
        self.layoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 30, 91, 251))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setGeometry(QtCore.QRect(110, 30, 301, 31))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 299, 29))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.textEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.textEdit.setGeometry(QtCore.QRect(0, 0, 301, 31))
        self.textEdit.setObjectName("textEdit")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea_2 = QtWidgets.QScrollArea(Dialog)
        self.scrollArea_2.setGeometry(QtCore.QRect(110, 70, 301, 31))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 299, 29))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.textEdit_2 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.textEdit_2.setGeometry(QtCore.QRect(0, 0, 301, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.scrollArea_3 = QtWidgets.QScrollArea(Dialog)
        self.scrollArea_3.setGeometry(QtCore.QRect(110, 120, 301, 31))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 299, 29))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.textEdit_3 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_3)
        self.textEdit_3.setGeometry(QtCore.QRect(0, 0, 301, 31))
        self.textEdit_3.setObjectName("textEdit_3")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.scrollArea_4 = QtWidgets.QScrollArea(Dialog)
        self.scrollArea_4.setGeometry(QtCore.QRect(110, 160, 301, 31))
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 299, 29))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.textEdit_4 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_4)
        self.textEdit_4.setGeometry(QtCore.QRect(0, 0, 301, 31))
        self.textEdit_4.setObjectName("textEdit_4")
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.scrollArea_5 = QtWidgets.QScrollArea(Dialog)
        self.scrollArea_5.setGeometry(QtCore.QRect(110, 210, 301, 31))
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 299, 29))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.textEdit_5 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_5)
        self.textEdit_5.setGeometry(QtCore.QRect(0, 0, 301, 31))
        self.textEdit_5.setObjectName("textEdit_5")
        today = date.today()
        self.textEdit_5.setPlainText(str(today))
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        # data = create_data_base.select_all_from_db()
        # for item in data:
        #     name = str(item[1])
        #     list_item = QtWidgets.QListWidgetItem(name)
        #     self.listWidget.addItem(list_item)
        # self.listWidget.itemClicked.connect(self.item_selected)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.pushButton_5.clicked.connect(self.save_data)



    def save_data1(self):
        print(1111)
    def save_data(self):
        desktop_path = os.path.join(os.path.expanduser("~"), "Desktop")

        data = {
            "Работник": self.textEdit.toPlainText(),
            "Товар": self.textEdit_2.toPlainText(),
            "Причина": self.textEdit_3.toPlainText(),
            "Склад №": self.textEdit_4.toPlainText(),
            "Дата": self.textEdit_5.toPlainText()
        }

        header = ["Работник", "Товар", "Причина", "Склад №", "Дата"]


        excel_file = os.path.join(desktop_path, "del_data.xlsx")
        wb = Workbook()
        ws = wb.active
        ws.append(header)
        row_data = [data[key] for key in header]
        ws.append(row_data)
        wb.save(excel_file)


        word_file = os.path.join(desktop_path, "del_data.docx")
        doc = Document()
        for key, value in data.items():
            doc.add_paragraph(f"{key}: {value}")
        doc.save(word_file)

        wb.save(excel_file)
    def item_selected(self, item):
        # Обработка события выбора элемента
        selected_text = item.text()
        print("Selected:", selected_text)
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_5.setText(_translate("Dialog", "Печать документов"))
        self.label.setText(_translate("Dialog", "Списание товара"))
        self.label_3.setText(_translate("Dialog", "Работник"))
        self.label_2.setText(_translate("Dialog", "Товар"))
        self.label_5.setText(_translate("Dialog", "Причина"))
        self.label_7.setText(_translate("Dialog", "Склад №"))
        self.label_6.setText(_translate("Dialog", "Дата"))


if __name__ == "__main__":
    import sys
    my_db = Data_base_meth()
    app = QApplication(sys.argv)
    dialog = Scroll_delete()
    dialog.show()
    sys.exit(app.exec_())


